### ISSUE TITLE
PHP 7 support

### ISSUE THREAD

**Issue by maikgreubel** [piece/stagehand-testrunner#46]
Run a test in Makegood with PHP 7 I get this error message:

    Fatal error: Cannot use Stagehand\TestRunner\Util\String as String because 'String' is a special class name

**Comment by maikgreubel** [comment]
Fixed by PR https://github.com/piece/stagehand-testrunner/pull/47

**Comment by iteman** [comment]
Thank you! :smile:

**Comment by FredericoGauz** [comment]
Hi, I am having the same problem when trying to use Make Good plugin in eclipse.

Fatal error: Cannot use Stagehand\TestRunner\Util\String as String because 'String' is a special class name in C:\Users\fgauz\Documents\development\eclipse\plugins\com.piece_framework.makegood.stagehandtestrunner_3.1.1.v201409021510\resources\php\vendor\piece\stagehand-testrunner\src\DependencyInjection\Transformation\Transformation.php on line 46

**Comment by gtsiou** [comment]
The problem is coming from the version of testrunner makegood is using and not the stagehand/testrunner itself. If you want a quick and dirty solution go to your `C:\Users\fgauz\Documents\development\eclipse\plugins\com.piece_framework.makegood.stagehandtestrunner_3.1.1.v201409021510\resources\php` and edit composer.json to look like this:

``` json
{
    "require": {
        "php": ">=5.3.3",
        "piece/stagehand-testrunner": "4.2.0",
        "phpunit/phpunit": "5.5.*"
    },
    "scripts": {
        "post-autoload-dump": [
            "Stagehand\\TestRunner\\Composer\\Script::compile"
        ]
    }
}
```

and then of course do a `compose update`.
